cquiroz/scala-java-time

README.md
build.sbt
jvm/src/test/scala/org/threeten/bp/UsabilityBasic.scala

This PR updates the location of the forked repository. Updates the version of scala-java-locales and removes a non-test that produced a largo amount of undesired output

Dependency updates and change repository

---

README.md
build.sbt
shared/src/main/scala/org/threeten/bp/format/DateTimeBuilder.scala

This PR updates the build file to copy the `org.threeten.bp` classes to `java.time` and do the proper package translation. This way the packages will include both packages

Java time packages

---

README.md
build.sbt
changes.xml
docs/src/main/tut/index.md

The scala-java-locales version has been downgraded to reduce the exported javascript size
Fixes #13

Prepare release 2.0.0-M7

---

js/src/main/scala/org/threeten/bp/zone/TzdbZoneRulesProvider.scala
project/plugins.sbt
project/src/main/scala/TZDBTasks.scala

This PR brings the latest time zone db which produces a much smaller output at the cost of readability.
A sample demo using a single timezone produces a fast/full optimized js of size:
* **before this PR**
fast/full
10501722/1517932
* **after this PR**
fast/full
2837605/981000
* Note that the size without tz usage is:
fast/full
1672688/372915
I don't expect this code to be the final way to provide a tzdb, instead a system where you can build your own db would produce smaller files and simpler to maintain
However this is already usable and could be released

Use optimized code generator

---

build.sbt
shared/src/main/scala/org/threeten/bp/Duration.scala
shared/src/main/scala/org/threeten/bp/Instant.scala
shared/src/main/scala/org/threeten/bp/LocalTime.scala
shared/src/main/scala/org/threeten/bp/OffsetDateTime.scala
shared/src/main/scala/org/threeten/bp/OffsetTime.scala
shared/src/main/scala/org/threeten/bp/ZoneOffset.scala
shared/src/main/scala/org/threeten/bp/zone/ZoneOffsetTransition.scala
shared/src/test/scala/org/threeten/bp/TestDayOfWeek.scala
shared/src/test/scala/org/threeten/bp/TestLocalTime.scala
shared/src/test/scala/org/threeten/bp/TestMonth.scala
shared/src/test/scala/org/threeten/bp/temporal/MockFieldNoValue.scala
shared/src/test/scala/org/threeten/bp/zone/TestFixedZoneRules.scala
shared/src/test/scala/org/threeten/bp/zone/TestZoneOffsetTransitionRule.scala
shared/src/test/scala/org/threeten/bp/zone/TestZoneRulesProvider.scala

This PR fixes #26 implementing `compareTo` on the affected classes
The build has been updated to run most tests on the `java.time` and `org.threeten.bp` packages to detect this kind of issues

Fix for compareTo

---

js/src/main/scala/java/util/TimeZone.scala

This PR improves the detection of the browser's time zone using the `Intl` API if available. Fixes #35 
Tested on Firefox, Safari, Chrome, Firefox ESR and node

Default ZoneId

---

build.sbt
js/src/main/scala/java/util/TimeZone.scala
js/src/test/scala/java/util/TestTimeZone.scala

Fixes #44. Just a _work in progress_ submission for enabling code review and discussion. The changes are focused on just the minimal effort needed to have #44 fixed and could benefit from some optimisations (i.e. some caching around the time zone localized names).
The small change in the `build.sbt` file is to ignore `.DS_Store` files that Macs usually create in folders when you navigate them, that was making compilation break when generating the `java.time` classes since the `replaceAll` functions where invoked in a binary file.

Add support for localized TimeZone names

---

changes.xml
js/src/main/scala/org/threeten/bp/zone/TzdbZoneRulesProvider.scala

This PR fixes some broken tests. The code below removed `UTC` and `GMT` from the list of zones like the java side does but that is a mistake

Fix for zone tests

---

.travis.yml
build.sbt
docs/src/main/tut/index.md
shared/src/main/scala/org/threeten/bp/ZonedDateTime.scala
shared/src/main/scala/org/threeten/bp/format/DateTimeFormatter.scala
shared/src/main/scala/org/threeten/bp/format/DateTimeFormatterBuilder.scala
shared/src/main/scala/org/threeten/bp/format/internal/TTBPDateTimeFormatterBuilder.scala
shared/src/main/scala/org/threeten/bp/format/internal/TTBPDateTimeTextProvider.scala
shared/src/main/scala/org/threeten/bp/format/internal/TTBPSimpleDateTimeTextProvider.scala
shared/src/test/scala/org/threeten/bp/TestZonedDateTime.scala
shared/src/test/scala/org/threeten/bp/format/TestDateTimeTextPrinting.scala
shared/src/test/scala/org/threeten/bp/format/TestSimpleDateTimeTextProvider.scala
shared/src/test/scala/org/threeten/bp/format/TestTextParser.scala
shared/src/test/scala/org/threeten/bp/format/TestTextPrinter.scala

The tests for `DateTimeTextPrinting` and `ZonedDateTime` were commented due to some compilation failures. This PR restores those tests fixing some incompatibilities with the original API due to the use of the scala `Long` class in some places

Restore skipped tests

---

build.sbt
changes.xml
shared/src/test/scala/org/threeten/bp/temporal/TestMonthDay.scala

Updated scala versions to the latest available

Scala 2.12.2 and 2.11.11

---

build.sbt
project/plugins.sbt

Though we can't test in 1.0.0-M2 we should be able to do a release nonetheless

Support building on scala.js 1.0.0-M2

---

README.md
build.sbt
changes.xml
core/js/src/main/scala/java/util/Calendar.scala
core/js/src/main/scala/java/util/GregorianCalendar.scala
core/js/src/main/scala/java/util/TimeZone.scala
docs/src/main/tut/index.md
project/plugins.sbt

This is the las PR for the M13 release.
It brings an important change. The binary will include only the java.time package
This reduces the size of the binary and speeds up compilation time for applications as there is less code to process
This assumes most people use `java.tima` rather than `org.threetrn` which is probably a good assumption

Only java packages on export

---

core/shared/src/main/scala/org/threeten/bp/zone/ZoneMap.scala
tests/js/src/test/scala/org/threeten/bp/Platform.scala
tests/jvm/src/test/scala/org/threeten/bp/Platform.scala
tests/shared/src/test/scala/java/util/TestZoneMap.scala

There are many unimplemented methods on ZoneMap, This improves the situation a lot. Related to #56

Implement most of ZoneMap

---

build.sbt
changes.xml
docs/src/main/tut/index.md
docs/src/main/tut/release_process.md
project/build.properties
project/plugins.sbt

Release 2.0.0-RC1

---

build.sbt

`sbtcrossproject.crossProject` is deprecated in favor of `sbtcrossproject.CrossPlugin.AutoImport`.

Fix deprecation warning on crossProject plugin

---

project/build.properties

https://www.lightbend.com/blog/sbt-1.3.0-release
sbt 1.3 introdues lots of enhancements.
Let's seethat scala-java-time works fine with sbt 1.3.0 or not.

Try sbt 1.3.0-RC1

---

.travis.yml

It seems that every build matrix fail after sbt 1.3.0-RC1.
https://travis-ci.org/exoego/scala-java-time/jobs/534310876#L685
This PR uses `find -delete` option to clear cache instead of `find | xargs rm` in case `rm` fails due to missing cache.
This is described in https://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html

Fix travis fails to handle empty cache in .ivy after sbt 1.3.0-RC1

---

.gitignore
.travis.yml
README.md
build.sbt
changes.xml
docs/src/main/tut/index.md
docs/src/main/tut/release_process.md
project/plugins.sbt
tests/jvm/src/test/scala/org/threeten/bp/UsabilityChrono.scala
tests/jvm/src/test/scala/org/threeten/bp/zone/TestTzdbZoneRulesCompiler.scala
tests/shared/src/test/scala/org/threeten/bp/FluentAPIChecker.scala
tests/shared/src/test/scala/org/threeten/bp/Performance.scala
tests/shared/src/test/scala/org/threeten/bp/chrono/TestChronoLocalDate.scala
tests/shared/src/test/scala/org/threeten/bp/chrono/TestChronoLocalDateTime.scala
tests/shared/src/test/scala/org/threeten/bp/chrono/TestChronoZonedDateTime.scala
tests/shared/src/test/scala/org/threeten/bp/chrono/TestChronology.scala
tests/shared/src/test/scala/org/threeten/bp/format/TestDateTimeFormatter.scala
tests/shared/src/test/scala/org/threeten/bp/format/TestDateTimeFormatters.scala
tests/shared/src/test/scala/org/threeten/bp/temporal/TestChronoUnit.scala

Support testing on 2.13.0-RC2 and update scalajs-locales

Scala 2.13.0 RC2 testing

---

core/shared/src/main/scala/org/threeten/bp/ZoneOffset.scala
core/shared/src/main/scala/org/threeten/bp/chrono/Chronology.scala
core/shared/src/main/scala/org/threeten/bp/format/DecimalStyle.scala
core/shared/src/main/scala/org/threeten/bp/format/SimpleDateTimeFormatStyleProvider.scala
core/shared/src/main/scala/org/threeten/bp/format/internal/TTBPSimpleDateTimeTextProvider.scala
core/shared/src/main/scala/org/threeten/bp/temporal/WeekFields.scala
core/shared/src/main/scala/org/threeten/bp/zone/StandardZoneRules.scala
core/shared/src/main/scala/org/threeten/bp/zone/ZoneRulesProvider.scala

We can remove the use of `ConcurrentHashMap` as we don't need on the JS world. This reduces fullOptJS in about 1% on my limited tests

Remove the use of ConcurrentHashMap

---

core/shared/src/main/scala/org/threeten/bp/chrono/HijrahChronology.scala
core/shared/src/main/scala/org/threeten/bp/chrono/IsoChronology.scala
core/shared/src/main/scala/org/threeten/bp/chrono/JapaneseChronology.scala
core/shared/src/main/scala/org/threeten/bp/chrono/MinguoChronology.scala
core/shared/src/main/scala/org/threeten/bp/chrono/ThaiBuddhistChronology.scala
core/shared/src/main/scala/org/threeten/bp/format/DateTimeBuilder.scala

On my PC, `sbt compile` aborts due to the compile error regarding this numeric widening.
I think this error is enabled by `tpolecat` plubin in https://github.com/cquiroz/scala-java-time/blob/master/project/plugins.sbt#L16
It is weird that CI ignores this error.

Fix implicit numeric widening

---

core/shared/src/main/scala/org/threeten/bp/Duration.scala
core/shared/src/main/scala/org/threeten/bp/Instant.scala
core/shared/src/main/scala/org/threeten/bp/ZoneId.scala
core/shared/src/main/scala/org/threeten/bp/ZoneOffset.scala
core/shared/src/main/scala/org/threeten/bp/format/DateTimeBuilder.scala
core/shared/src/main/scala/org/threeten/bp/format/DateTimeFormatter.scala
core/shared/src/main/scala/org/threeten/bp/format/DateTimeFormatterBuilder.scala
core/shared/src/main/scala/org/threeten/bp/format/internal/TTBPDateTimeTextProvider.scala
core/shared/src/main/scala/org/threeten/bp/temporal/IsoFields.scala
core/shared/src/main/scala/org/threeten/bp/temporal/JulianFields.scala
core/shared/src/main/scala/org/threeten/bp/temporal/TemporalAdjusters.scala
core/shared/src/main/scala/org/threeten/bp/temporal/TemporalQueries.scala
core/shared/src/main/scala/org/threeten/bp/temporal/ValueRange.scala
core/shared/src/main/scala/org/threeten/bp/temporal/WeekFields.scala
core/shared/src/main/scala/org/threeten/bp/temporal/package.scala
tests/shared/src/test/scala/org/threeten/bp/format/TestSimpleDateTimeTextProvider.scala
tests/shared/src/test/scala/org/threeten/bp/format/TestTextParser.scala
tests/shared/src/test/scala/org/threeten/bp/format/TestTextPrinter.scala

some improvements reducing size by about 2%

Size reductions

---

.jvmopts

It fixes the slowdown and OOM errors with hanging when running the `sbt clean test` command:
```
[info] Fast optimizing /home/andriy/Projects/com/github/plokhotnyuk/scala-java-time/tests/js/target/scala-2.13/scala-java-time-tests-test-fastopt.js
Exception in thread "task-progress-report-thread" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "task-progress-report-thread"
Exception in thread "classloader-cache-cleanup-0" java.lang.OutOfMemoryError: Java heap space
at scala.runtime.IntRef.create(IntRef.java:23)
at scala.util.hashing.MurmurHash3.unorderedHash(MurmurHash3.scala:94)
at scala.util.hashing.MurmurHash3$.setHash(MurmurHash3.scala:230)
at scala.collection.GenSetLike.hashCode(GenSetLike.scala:135)
at …
```

Fix of OOM errors during compiling and testing the whole project in a batch more

---

core/js/src/main/scala/java/util/TimeZone.scala

Theoretically, `contains(v)` is a bit faster and create less garbage, since it does not require a predicate function.
Sorry, not measured actual metrics.

[refactoring] Replace exists(_ == v) with contains(v) 

---

README.md
build.sbt

Update scala 3

---

core/jvm/src/main/scala/org/threeten/bp/chrono/HijrahDateConfigurator.scala
core/shared/src/main/scala/org/threeten/bp/Duration.scala
core/shared/src/main/scala/org/threeten/bp/LocalTime.scala
core/shared/src/main/scala/org/threeten/bp/chrono/ChronoLocalDateTimeImpl.scala
core/shared/src/main/scala/org/threeten/bp/chrono/HijrahDate.scala
core/shared/src/main/scala/org/threeten/bp/zone/StandardZoneRules.scala

> A constant value definition is of the form
> ```scala
> final val x = e
> ```
> where `e` is a [constant expression](https://www.scala-lang.org/files/archive/spec/2.13/06-expressions.html#constant-expressions). The final modifier must be present and no type annotation may be given. References to the constant value `x` are themselves treated as constant expressions; in the generated code they are replaced by the definition's right-hand side `e`.
https://www.scala-lang.org/files/archive/spec/2.13/04-basic-declarations-and-definitions.html#value-declarations-and-definitions

Declare constants properly

---

.envrc
.github/workflows/scala.yml
.gitignore
core/shared/src/main/scala-2/org/threeten/bp/temporal/IsoFields.scala
core/shared/src/main/scala-3/org/threeten/bp/temporal/IsoFields.scala
core/shared/src/main/scala/org/threeten/bp/Duration.scala
flake.lock
flake.nix
tests/shared/src/test/scala/org/threeten/bp/TestDuration.scala

Partially fixes https://github.com/cquiroz/scala-java-time/issues/254

Duration Java 9 methods

---

.github/workflows/ci.yml
.jvmopts
build.sbt
project/plugins.sbt

The GHA macOS runner has 2x more RAM than the ubuntu runner.

Run Scala 3 / Native job on macOS

---

build.sbt
core/shared/src/main/scala/org/threeten/bp/ZoneOffset.scala

Closes #518 
It seems that this used to work, but relied on the fact that `ZoneOffset.UTC` will put "Z" in 
ID_CACHE when object is initialised.
This no longer works because ZoneOffset.UTC was made into a lazy val, so invoking `ZoneOffset.of("Z")` will not trigger the `ZoneOffset.UTC` calculation.
To confirm, just touching ZoneOffset.UTC is enough to make repro work:
```
scala-cli -e 'java.time.ZoneOffset.UTC;java.time.ZoneOffset.of("Z")' --js --dep io.github.cquiroz::scala-java-time::2.6.0 # succeeds
```
I feel like relying on this cache behaviour is too brittle, so I decided to explictly special-case "Z" as it's a special case in java docs as well.
---
Note that this case is already tested, but one of the previous tests refers to ZoneOffset.UTC, triggering the cache update.

ZoneOffset.of("Z") must return UTC

---

.gitignore
build.sbt

I think this is the best I can do for https://github.com/cquiroz/scala-java-time/issues/519
scala-java-time build does some non-standard things that make supporting fully correct source maps pretty hard. But, we can get pretty close. This PR fixes the URLs for all source maps under `core/shared`. Unfortunately, the source maps for `core/js` remain broken, but most files are in `shared`. Someone strong in sbt may be able to improve on this, but absent of that, my vote is that it's good enough.
Also, scala-java-time build transforms the content of the source files (changes packages / imports / etc.) – FYI, to the extent that this modifies positions of terms in the source code, this could break source maps as well. But, most of the transformations are line-for-line replacements of imports …

Fix source map URLs (as much as possible). Fixes #519
