- .gitignore
- README.md
- build.sbt
- docs/src/main/tut/index.md
- docs/src/main/tut/release_process.md
- project/plugins.sbt
Small updates to the build to support making a proper release
> Release info

- project/plugins.sbt
To make it compatible with ensime
> Update coursier version

- js/src/test/scala/java/util/TestTimeZone.scala
> Simple test for java.util.TimeZone replacement

- build.sbt
- changes.xml
- docs/src/main/tut/index.md
> Don't include the java.time classes on the JVM side

- build.sbt
> Points to githubusercontent for scala.js sourcemaps

- build.sbt
- changes.xml
Better source mappings fixes #29
> Improve source mappings

- .travis.yml
- build.sbt
Some improvements to the build to cover more node versions and match `scala-java-locales` build parameters
> Build improvements

- build.sbt
- docs/src/main/tut/release_process.md
- project/plugins.sbt
> Updates to sbt-microsites and sbt-coursier

- build.sbt
- project/plugins.sbt
Update to scala.js 0.6.17 for a very nice speed bump when building the tests
> Update scalajs and setup next release version

- .travis.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
- shared/src/test/scala/org/threeten/bp/TestZonedDateTime.scala
Multiple updates to scala and node versions and use sbt 1.0.x
> Libupdates

- build.sbt
- changes.xml
- docs/src/main/tut/index.md
- docs/src/main/tut/release_process.md
- project/plugins.sbt
Add support for Scala.js 1.0.0-M3
> Scalajs 1.0.0 m3

- build.sbt
Tiny change to properly do the release
> Remove scm to properly release

- .travis.yml
- build.sbt
- core/shared/src/main/scala/org/threeten/bp/zone/ZoneRulesBuilder.scala
- project/build.properties
- project/plugins.sbt
Across the board library updates
> Library updates

- .travis.yml
- build.sbt
- project/build.properties
Release notes
* [Scala 2.12.7](https://github.com/scala/scala/releases/tag/v2.12.7): Faster compilation is remarkable.
* [Scala 2.13.0-M5](https://github.com/scala/scala/releases/tag/v2.13.0-M5)
* [sbt 1.2.3](https://developer.lightbend.com/blog/2018-09-14-sbt-1-2-3/index.html)
> [WIP] Update Scala & sbt.

- build.sbt
- project/plugins.sbt
- tests/js/src/test/scala/org/threeten/bp/zone/TestStandardZoneRulesNegativeTZDB.scala
- tests/shared/src/test/scala/org/threeten/bp/zone/TestStandardZoneRules.scala
> Update tzdb version

- .travis.yml
- README.md
- build.sbt
- changes.xml
- core/shared/src/main/scala/org/threeten/bp/LocalDateTime.scala
- core/shared/src/main/scala/org/threeten/bp/ZoneId.scala
- core/shared/src/main/scala/org/threeten/bp/ZonedDateTime.scala
- core/shared/src/main/scala/org/threeten/bp/format/DateTimeBuilder.scala
- core/shared/src/main/scala/org/threeten/bp/format/DateTimeFormatter.scala
- core/shared/src/main/scala/org/threeten/bp/format/DateTimeFormatterBuilder.scala
- core/shared/src/main/scala/org/threeten/bp/format/DecimalStyle.scala
- core/shared/src/main/scala/org/threeten/bp/format/SimpleDateTimeFormatStyleProvider.scala
- core/shared/src/main/scala/org/threeten/bp/format/internal/TTBPDateTimeFormatterBuilder.scala
- core/shared/src/main/scala/org/threeten/bp/format/internal/TTBPDateTimeParseContext.scala
- core/shared/src/main/scala/org/threeten/bp/format/internal/TTBPDateTimePrintContext.scala
- core/shared/src/main/scala/org/threeten/bp/format/internal/TTBPDateTimeTextProvider.scala
- core/shared/src/main/scala/org/threeten/bp/format/internal/TTBPSimpleDateTimeTextProvider.scala
- core/shared/src/main/scala/org/threeten/bp/zone/ZoneRulesBuilder.scala
- project/plugins.sbt
This PR includes refactoring to reduce a bit the size of the produced output and prepares the next release
> Refactorings

- build.sbt
- core/js/src/main/scala/java/util/TimeZone.scala
- project/plugins.sbt
> Last minute fixes

- core/shared/src/main/scala/org/threeten/bp/ZoneId.scala
- tests/shared/src/test/scala/org/threeten/bp/TestZoneId.scala
> Fix message for unknown zoneid error

- .github/release-drafter.yml
> Add drafter template

- .github/workflows/scala.yml
- build.sbt
> Fix running test on the latest jvm

- .github/workflows/release.yml
- .github/workflows/scala.yml
- project/build.properties
> Update sbt and fix release task

- build.sbt
- project/plugins.sbt
> Upgrade to scala.js 1.2.0

- CHANGELOG.md
- README.md
- build.sbt
> Support scala 3.0.0-M3

- build.sbt
- core/shared/src/main/scala-3.x/org/threeten/bp/zone/ZoneMap.scala
- project/plugins.sbt
- tests/shared/src/test/scala/org/threeten/bp/TestDayOfWeek.scala
- tests/shared/src/test/scala/org/threeten/bp/TestLocalDate.scala
- tests/shared/src/test/scala/org/threeten/bp/TestLocalDateTime.scala
- tests/shared/src/test/scala/org/threeten/bp/TestLocalTime.scala
- tests/shared/src/test/scala/org/threeten/bp/TestOffsetDateTime.scala
- tests/shared/src/test/scala/org/threeten/bp/TestOffsetTime.scala
- tests/shared/src/test/scala/org/threeten/bp/TestPeriod.scala
- tests/shared/src/test/scala/org/threeten/bp/TestZonedDateTime.scala
- tests/shared/src/test/scala/org/threeten/bp/temporal/TestYear.scala
- tests/shared/src/test/scala/org/threeten/bp/temporal/TestYearMonth.scala
Supports scala 3.0.0-M1 and scala.js 1.5.0
> Support scala 3.0.0-M1

- .github/workflows/release.yml
> Don't setup gpg
